version: '3.8'

services:
  redis:
    image: redis:7.2.4-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --requirepass mysecretpassword --appendonly yes

volumes:
  redis-data: